### ISSUE TITLE
Problems with FragGeneScan

### ISSUE THREAD

**Issue by giuliodimaria92** [xiezhq/ISEScan#11]
Good evening...I can't find this programme. How can I solve the problem? Thank you!

isPredict begins at Fri May  3 17:39:37 2019

Begin to translate genome into proteome.
/bin/sh: 1: /u/zhiqxie/informatics/inst/FragGeneScan1.30/run_FragGeneScan.pl: not found
Translating genome into proteome for /home/usuario/anaconda3/envs/IScan/ISEScan-master/NC_012624.fna , return error!

Finish translating genome into proteome. Fri May  3 17:39:37 2019
No such file or Empty file prueba/ISEScan-master/NC_012624.fna.faa
No such file or Empty file prueba/ISEScan-master/NC_012624.fna.faa
No hit was returned by HMM search against protein database. Fri May  3 17:39:37 2019
isPredict ends at Fri May  3 17:39:37 2019
(IScan) usuario@pra-dpt-62660:~/anaconda3/envs/IScan/ISEScan-master$ python3 isescan.py ~/anaconda3/envs/IScan/ISEScan-master/NC_012624.fna prueba hmm
isPredict begins at Fri May  3 17:40:56 2019

**Comment by xiezhq** [comment]
You need to configure ISEScan before you run it because the paths of the required pakcages installed on your computer might be different from those on my computer. 

Please go to https://github.com/xiezhq/ISEScan, and find 'Configure ISEScan' and follow the instructions there to configure your isescan environment. For example, in your case, the error showed the path pointing to the installed FragGeneScan on my computer, /u/zhiqxie/informatics/inst/FragGeneScan1.30/run_FragGeneScan.pl. You need to change it to the path pointing to the FragGeneScan installed on your computer at line 10 in constants.py. You may also need to change other paths in constants.py to match the correct paths where the required packages are installed on your computer.

Hope it is helpful.

Good luck,
Jason

**Comment by giuliodimaria92** [comment]
Good morning! FragGeneScan now works and I've changed all the paths but...
It generated only 5 files (the first four have content) with format problems:
NC_012624.fna.faa 
NC_012624.fna.ffn
NC_012624.fna.gff
NC_012624.fna.out
clusters.faa.hmm.NC_012624.fna.faa (it is empty)

Begin to translate genome into proteome.
/home/usuario/anaconda3/envs/IScan/FragGeneScan1.30/FragGeneScan -s /home/usuario/anaconda3/envs/IScan/ISEScan-master/NC_012624.fna -o prueba/ISEScan-master/NC_012624.fna -w 0 -t illumina_5 -p 4
Using 4 threads.
no. of seqs: 1
Clock time used (by 4 threads) = 0.01 mins
prepare gff file..
Time elapsed: 0 hours 0 minutes and 1 seconds.
Translating genome into proteome for /home/usuario/anaconda3/envs/IScan/ISEScan-master/NC_012624.fna , return  0

Finish translating genome into proteome. Mon May 13 12:32:35 2019

Begin to phmmer search against proteome database. Mon May 13 12:32:35 2019

Error: Sequence file /home/usuario/anaconda3/envs/IScan/ISEScan-master/pHMMs/clusters.faa.hmm is empty or misformatted

Traceback (most recent call last):
  File "isescan.py", line 57, in <module>
    isPredictSingle(args4isPredictSingle)
  File "isescan.py", line 22, in isPredictSingle
    isPredict.isPredict(filelist, path2proteome, path2hmm)
  File "/home/usuario/anaconda3/envs/IScan/ISEScan-master/isPredict.py", line 263, in isPredict
    phmmerSearch(args2concurrent4phmmer)
  File "/home/usuario/anaconda3/envs/IScan/ISEScan-master/isPredict.py", line 176, in phmmerSearch
    raise RuntimeError(e)
RuntimeError: phmmer searching /home/usuario/anaconda3/envs/IScan/ISEScan-master/pHMMs/clusters.faa.hmm against prueba/ISEScan-master/NC_012624.fna.faa, return error!

Thank you for the help!

**Comment by xiezhq** [comment]
Please go to your work directory, and then run three commands and show me the outputs of these commands:
pwd
ls -lh /home/usuario/anaconda3/envs/IScan/ISEScan-master/pHMMs/

And, how did you run isescan.py on your computer?

**Comment by giuliodimaria92** [comment]
Good evening...
(base) usuario@pra-dpt-62660:~$ source deactivate
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
usuario@pra-dpt-62660:~$ pwd
/home/usuario
usuario@pra-dpt-62660:~$ ls -lh /home/usuario/anaconda3/envs/IScan/ISEScan-master/pHMMs/
total 39M
-rw-rw-r-- 1 usuario usuario 39M abr  7 10:55 clusters.faa.hmm
-rw-rw-r-- 1 usuario usuario 98K abr  7 10:55 clusters.single.faa
usuario@pra-dpt-62660:~$ ^C
usuario@pra-dpt-62660:~$
I'm working with my PC in the environment of Anaconda
Thank you!

**Comment by giuliodimaria92** [comment]
usuario@pra-dpt-62660:~$ pwd
/home/usuario
usuario@pra-dpt-62660:~$ ls -lh /home/usuario/anaconda3/envs/IScan/ISEScan-master/pHMMs/
total 39M
-rw-rw-r-- 1 usuario usuario 39M abr  7 10:55 clusters.faa.hmm
-rw-rw-r-- 1 usuario usuario 98K abr  7 10:55 clusters.single.faa

**Comment by xiezhq** [comment]
The problem might be caused by the path pointing to the profile HMM files (clusters.single.faa and clusters.faa.hmm). Please download two updated files, constants.py and isPredict.py from https://github.com/xiezhq/ISEScan/blob/master/, and then try running isescan again. Please let me know if it solves your problem or not. Thank you!

**Comment by giuliodimaria92** [comment]
Good evening...how to access to update Aclame database? Thank you! :)

**Comment by xiezhq** [comment]
You can download ACLAME database from http://aclame.ulb.ac.be/ but it has not been updated since version 0.4 (2009).

**Comment by xiezhq** [comment]
The issue is closed as no more problem was reported.
